//! Generation of the scratch crate.
//!
//! The scratch crate is a minimal binary package the collector writes
//! under `<target_directory>/frieze/<package>/`. Its only job is to
//! link the target crate — so the schema registrations embedded in the
//! target's derive output are present in a running binary — and dump
//! the canonical components to stdout as JSON. Placing it under the
//! build directory keeps it out of the user's sources, persists the
//! incremental-build cache between runs, and lets `cargo clean` remove
//! it.
//!
//! Both generated files are unconditionally overwritten on every run,
//! so stale content can never survive a frieze upgrade.

use std::path::{Path, PathBuf};

use frieze_model::{CargoFeatureName, PackageName, PackageRoot};

use crate::inspect::PackageInspection;
use crate::Error;

/// The environment variable that redirects the scratch crate's
/// `frieze` / `frieze-usecase` dependencies to a local checkout of
/// this workspace (its value is the checkout's root directory).
///
/// This exists for this repository's own end-to-end tests, which must
/// resolve the unpublished frieze crates by path; it is not part of
/// the public contract. When unset, the scratch crate depends on the
/// crates.io releases pinned to this crate's own version.
pub(crate) const LOCAL_CRATES_DIR_ENV: &str = "FRIEZE_LOCAL_CRATES_DIR";

/// Writes (or rewrites) the scratch crate for `package_name` and
/// returns its directory.
pub(crate) fn prepare_scratch(
    root: &PackageRoot,
    package_name: &PackageName,
    features: &[CargoFeatureName],
    inspection: &PackageInspection,
) -> Result<PathBuf, Error> {
    let scratch_dir = inspection
        .target_directory
        .join("frieze")
        .join(package_name.as_str());
    std::fs::create_dir_all(scratch_dir.join("src")).map_err(Error::ScratchIo)?;
    std::fs::write(
        scratch_dir.join("Cargo.toml"),
        scratch_manifest(root, package_name, features),
    )
    .map_err(Error::ScratchTemplateWrite)?;
    std::fs::write(
        scratch_dir.join("src").join("main.rs"),
        scratch_main(&inspection.lib_crate_name),
    )
    .map_err(Error::ScratchTemplateWrite)?;
    share_lockfile(&inspection.workspace_root, &scratch_dir)?;
    Ok(scratch_dir)
}

/// Renders the scratch crate's `Cargo.toml`.
///
/// The target crate is a path dependency, so cargo's own change
/// detection rebuilds the scratch binary exactly when the target crate
/// changed. The cargo features declared under
/// `[package.metadata.frieze] features` are transcribed onto that
/// dependency, so the scratch build compiles the target with exactly
/// the configuration the metadata asks for. The `inventory` feature of
/// frieze is always requested here (the scratch binary is what
/// iterates the registrations); whether the *target* crate submits
/// anything is governed by the target's own dependency declaration and
/// checked before this file is written.
///
/// The empty `[workspace]` table keeps the scratch crate a standalone
/// workspace even when the build directory sits inside the user's.
fn scratch_manifest(
    root: &PackageRoot,
    package_name: &PackageName,
    features: &[CargoFeatureName],
) -> String {
    let version = env!("CARGO_PKG_VERSION");
    let (frieze_dep, frieze_usecase_dep) = match std::env::var_os(LOCAL_CRATES_DIR_ENV) {
        Some(dir) => {
            let dir = Path::new(&dir);
            (
                format!(
                    "{{ path = {}, features = [\"inventory\"] }}",
                    toml_string(&dir.join("crates/libs/frieze").display().to_string())
                ),
                format!(
                    "{{ path = {} }}",
                    toml_string(
                        &dir.join("crates/domain/frieze-usecase")
                            .display()
                            .to_string()
                    )
                ),
            )
        }
        None => (
            format!("{{ version = \"={version}\", features = [\"inventory\"] }}"),
            format!("{{ version = \"={version}\" }}"),
        ),
    };
    format!(
        r#"# Generated by frieze; overwritten on every generate run. Do not edit.

[package]
name = "frieze-scratch-{package_name}"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
{package_name} = {{ path = {root_path}{features} }}
frieze = {frieze_dep}
frieze-usecase = {frieze_usecase_dep}
serde_json = "1"

[workspace]
"#,
        root_path = toml_string(&root.as_path().display().to_string()),
        features = features_fragment(features),
    )
}

/// Renders the `features = [...]` fragment of the target dependency,
/// or nothing when the metadata declares no features — the minimal
/// manifest stays minimal.
fn features_fragment(features: &[CargoFeatureName]) -> String {
    if features.is_empty() {
        return String::new();
    }
    let list = features
        .iter()
        .map(|feature| toml_string(feature.as_str()))
        .collect::<Vec<_>>()
        .join(", ");
    format!(", features = [{list}]")
}

/// Renders the scratch crate's `main.rs`. The only interpolated value
/// is the target crate's name.
///
/// The `use ... as _;` line is what guarantees the collection works:
/// naming the target crate makes it part of the scratch binary's crate
/// graph, so its rlib — including the linker-section registration
/// entries emitted by `#[derive(Schema)]` under the `inventory`
/// feature — is linked into the binary that `from_inventory()` then
/// iterates.
fn scratch_main(lib_crate_name: &str) -> String {
    format!(
        r#"//! Generated by frieze; overwritten on every generate run. Do not edit.

// Naming the target crate links it into this binary, keeping its
// schema registrations reachable for the inventory iteration below.
use {lib_crate_name} as _;

fn main() -> Result<(), Box<dyn std::error::Error>> {{
    let schemas = frieze::SchemasBuilder::new().from_inventory().build()?;
    let components = frieze_usecase::components_from_schemas(&schemas);
    serde_json::to_writer(std::io::stdout().lock(), &components)?;
    Ok(())
}}
"#
    )
}

/// Seeds the scratch crate's `Cargo.lock` with the workspace's, so the
/// transitive dependency versions of the target crate resolve
/// identically in both builds.
///
/// The lockfile is **copied**, never symlinked: cargo rewrites the
/// scratch lockfile (the scratch crate has dependencies of its own),
/// and it writes through symlinks — a symlinked lockfile would get the
/// user's `Cargo.lock` overwritten with scratch-only entries. Copying
/// on every run keeps the shared versions in sync at the cost of cargo
/// re-adding the scratch-only entries each time.
fn share_lockfile(workspace_root: &Path, scratch_dir: &Path) -> Result<(), Error> {
    let source = workspace_root.join("Cargo.lock");
    if !source.is_file() {
        // A workspace that has never been built has no lockfile yet;
        // the scratch build will resolve fresh, and so will the
        // workspace when it is built. Nothing to share.
        return Ok(());
    }
    let destination = scratch_dir.join("Cargo.lock");
    std::fs::copy(&source, &destination)
        .map(drop)
        .map_err(Error::ScratchIo)
}

/// Quotes `value` as a TOML basic string.
fn toml_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn root_in(dir: &Path) -> PackageRoot {
        std::fs::write(dir.join("Cargo.toml"), "[package]\n").unwrap();
        PackageRoot::try_from_path(dir).unwrap()
    }

    #[test]
    fn manifest_declares_the_target_as_a_path_dependency() {
        let dir = tempfile::tempdir().unwrap();
        let root = root_in(dir.path());
        let manifest = scratch_manifest(&root, &PackageName::new("my-api").unwrap(), &[]);
        assert!(manifest.contains("name = \"frieze-scratch-my-api\""));
        assert!(
            manifest.contains(&format!(
                "my-api = {{ path = \"{}\" }}",
                root.as_path().display()
            )),
            "manifest should point the path dependency at the package root:\n{manifest}"
        );
        assert!(manifest.contains("features = [\"inventory\"]"));
        assert!(
            manifest.contains("\n[workspace]\n"),
            "the scratch crate must opt out of any enclosing workspace"
        );
    }

    #[test]
    fn manifest_transcribes_the_declared_features_onto_the_target_dependency() {
        let dir = tempfile::tempdir().unwrap();
        let root = root_in(dir.path());
        let features = [
            CargoFeatureName::new("extra").unwrap(),
            CargoFeatureName::new("json-schema").unwrap(),
        ];
        let manifest = scratch_manifest(&root, &PackageName::new("my-api").unwrap(), &features);
        assert!(
            manifest.contains(&format!(
                "my-api = {{ path = \"{}\", features = [\"extra\", \"json-schema\"] }}",
                root.as_path().display()
            )),
            "manifest should enable the declared features on the target:\n{manifest}"
        );
    }

    #[test]
    fn main_names_the_target_crate() {
        let main = scratch_main("my_api");
        assert!(main.contains("use my_api as _;"), "got:\n{main}");
        assert!(main.contains("from_inventory()"));
        assert!(main.contains("components_from_schemas"));
    }

    #[test]
    fn lockfile_is_copied_not_symlinked() {
        let workspace = tempfile::tempdir().unwrap();
        let scratch = tempfile::tempdir().unwrap();
        std::fs::write(workspace.path().join("Cargo.lock"), "version = 4\n").unwrap();
        share_lockfile(workspace.path(), scratch.path()).unwrap();
        let copied = scratch.path().join("Cargo.lock");
        assert!(copied.is_file());
        assert!(
            !copied.symlink_metadata().unwrap().file_type().is_symlink(),
            "the scratch lockfile must be an independent copy"
        );
        assert_eq!(std::fs::read_to_string(&copied).unwrap(), "version = 4\n");
    }

    #[test]
    fn a_missing_workspace_lockfile_is_not_an_error() {
        let workspace = tempfile::tempdir().unwrap();
        let scratch = tempfile::tempdir().unwrap();
        share_lockfile(workspace.path(), scratch.path()).unwrap();
        assert!(!scratch.path().join("Cargo.lock").exists());
    }
}
